### PR TITLE
Build rolenameor environment

### PR DESCRIPTION
**Pull request by Outek**
adding functionality to build Mof files only for a specific Role or for an environment.

### CODE REVIEW

**Comment by raandree** [comment]
Thank for using DscWorkshop and participating in the development. Quite some time ago somebody was adding a filter parameter to the build script that can be used to filter for any node property

```PowerShell
.\Build.ps1 -Filter { $_.Environment -eq 'Dev' -and $_.Role -eq 'FileServer' }
```

Is this concept doing what you need?

**Comment by Outek** [comment]
Yes, this is the same. I found it a little easier to Filter with a Parameter
```powershell
.\Build.ps1 -Environment Dev
```
Should i close the MR?

**Comment by gaelcolas** [comment]
I think so, Environment is specific to this layered architecture. One could use this without Environment and call it 'stages'

**Comment by raandree** [comment]
Right, I was implementing more switches when starting with @gaelcolas projects and then realized that each of my customers has a different setup. This is why we added the generic filter parameter.

What you can do is add your own build script that implements the parameter patterns to make you life easier and translate your input into a filter.

**Pull request closed without merging**
